version: 2

sources:
  - name: raw
    tables:
      - name: events
      - name: orders
      - name: users

models:
  - name: stg_events
    description: "Staged events table"
    columns:
      - name: event_id
        tests:
          - unique
          - not_null